### ISSUE TITLE
Error after bundle install. `undefined method `gsub' for #<Array:0x007f811792bec8> (NoMethodError)`

### ISSUE THREAD

**Issue by xn** [code-and-effect/effective_assets#5]
```
rails c
/Users/xn/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:128:in `escape': undefined method `gsub' for #<Array:0x007f811792bec8> (NoMethodError)
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:122:in `block in compile_glob'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:121:in `each'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:121:in `map'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:121:in `compile_glob'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:40:in `initialize'
	from /Users/xn/.rvm/gems/ruby-2.2.1/bundler/gems/activeadmin-8968efcc51cc/lib/active_admin/application.rb:280:in `new'
	from /Users/xn/.rvm/gems/ruby-2.2.1/bundler/gems/activeadmin-8968efcc51cc/lib/active_admin/application.rb:280:in `block in attach_reloader'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:36:in `call'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application/finisher.rb:62:in `block in <module:Finisher>'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/xn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/xn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/xn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/xn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/xn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/xn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/xn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/xn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/xn/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
	from /Users/xn/sites/contraption/education/config/environment.rb:5:in `<top (required)>'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/application.rb:328:in `require_environment!'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:67:in `console'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/xn/.rvm/gems/ruby-2.2.1/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by xn** [comment]
Gemfile
```
source 'https://rubygems.org'
ruby "2.2.1"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
# Use postgresql as the database for Active Record
gem 'pg'
gem 'rails_12factor', group: :production
gem 'puma'

gem 'activeadmin', github: 'activeadmin'
gem 'acts_as_list'
gem 'bootstrap-generators', git: 'git://github.com/decioferreira/bootstrap-generators.git'
gem 'coffee-rails', '~> 4.1.0'
gem 'devise'
gem 'effective_assets', github: 'code-and-effect/effective_assets', require: false
gem 'haml-rails'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'sass-rails', '~> 5.0'
gem 'simple_form'
gem 'uglifier', '>= 1.3.0'
gem 'cocoon'

group :development, :test do
  gem 'annotate'
  gem 'pry'
  gem 'web-console', '~> 2.0'
end
```

**Comment by xn** [comment]
I was able to get around it by adding: `require: false` to the effective_assets declaration and then add the require to an initializer.
I'm going to move forward from here and see if I can still get it to work. I've got a ton of work today but will try and sort this out.

**Comment by xn** [comment]
btw, I tried both the plain gem and the github version

**Comment by jfeaver** [comment]
Hi @xn,
Thanks for posting the issue.  I don't immediately see any issues with the code.  Do let us know if you make any progress on it and we'll do the same :)

**Comment by xn** [comment]
I removed ActiveAdmin and the problem went away. Honing in.

**Comment by xn** [comment]
This is the commit where it blows up:
https://github.com/activeadmin/activeadmin/commit/b18d8cc8ce114af878dd997d7d2772ae44ed2b0d

So, there is no error here: `gem 'activeadmin', github: 'activeadmin', ref: '3f916d6'`

**Comment by matt-riemer** [comment]
Hey xn!

Thanks so much for your interest in effective_assets :)

I have reproduced your error locally.
I get the same  `escape': undefined method `gsub' for #<Array:0x007fa634635e70>

If I remove effective_assets entirely, I still receive this same error.

I believe this is an issue on the master branch of activeadmin.  I'd suggest using a release version instead of the master.

Thanks

**Comment by xn** [comment]
I was in the middle of opening an issue on AA. :) 

I've been working on this codebase all day and, for whatever reason, the issue started when I installed this gem.

(I'm spiking something out and wanted to play with your gem)

Thanks!

**Comment by matt-riemer** [comment]
You are an excellent open source citizen, thank you :)

**Comment by timoschilling** [comment]
Please reopen this Issue. It's a `effective_assets` bug not a `ActiveAdmin` one.

`effective_assets` has a wrong handling of his `load_paths` extending for `ActiveAdmin`.
